version: '3.3'

services:
  server:
    build: .
    volumes:
      - 'data:/go:rw'
      - '.:/go/src/go-grpc'
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c 'cd /go/src/go-grpc/server && go run server.go'
  client:
    build: .
    volumes:
      - 'data:/go:rw'
      - '.:/go/src/go-grpc'
    # expose:
    #   - 8080
    links:
      - server
    command: bash -c 'cd /go/src/go-grpc/client && go run client.go'
volumes:
  data:
    driver: 'local'
