version: 2
jobs:
  build:
    docker:
      machine: true
      steps:
        - checkout
        - run: docker-compose run server glide install
        - run: docker-compose run server go test -v -cover ./...
